source 'https://rubygems.org'
gem 'ffi'
gem 'colorize'
gem 'ruby-prof'
gem 'rasem'
gem 'lru_redux'
gem 'ruby-fann', git: 'https://github.com/tangledpath/ruby-fann.git', tag: 'v1.2.5'
gem 'em-websocket'
gem 'pokereval', path: '/home/mikec/ruby/ruby-pokereval'
gem 'sqlite3'
gem 'byebug'
